-- =====================================================================
-- Seed from the live Google Sheet, exported 2026-09-26T04:25:50.920Z
--
-- Generated by scratchpad/gen_seed.js from a raw TAB_HEADERS dump, so
-- every value is a literal copy of what is in the Sheet right now.
-- Re-runnable: every insert is ON CONFLICT DO UPDATE.
-- =====================================================================

-- models
insert into models (model_name, parts_per_unit, updated_at) values (
  '3004', '{"BACK (883x1874)":{"qty":1,"size":"883x1874"},"BOTTOM (893x582)":{"qty":1,"size":"893x582"},"TOP (893x582)":{"qty":1,"size":"893X582"},"SIDE (1884x566)":{"qty":2,"size":"118X566"},"DOOR L (477x1850)":{"qty":1,"size":"477X1850"},"DOOR R (467x1850)":{"qty":1,"size":"467X1850"},"SHELF (510x890)":{"qty":4,"size":"510X890"},"SIDE SUPPORT (80x1730)":{"qty":1,"size":"80X1730"},"SIDE SUPPORT (120x1780)":{"qty":2,"size":"120X1780"},"LEG (1060x178)":{"qty":2,"size":"1060X178"},"LOCKER COVER":{"qty":2,"size":"N/A"}}'::jsonb, '2026-09-13T06:18:16.829Z'::timestamptz)
on conflict (model_name) do update set
  parts_per_unit = excluded.parts_per_unit, updated_at = excluded.updated_at;

-- cutting_plans
insert into cutting_plans (model_name, plan_name, sheets, plan_type, base_qty, updated_at) values (
  '3004', 'Plan 1', '[{"width":900,"height":2500,"thickness":0.45,"outputs":[{"partName":"BACK (883x1874)","qty":1},{"partName":"BOTTOM (893x582)","qty":1}]},{"width":900,"height":2500,"thickness":0.45,"outputs":[{"partName":"SHELF (510x890)","qty":4}]},{"width":900,"height":2500,"thickness":0.5,"outputs":[{"partName":"DOOR L (477x1850)","qty":1},{"partName":"DOOR R (467x1850)","qty":1},{"partName":"TOP (893x582)","qty":1}]},{"width":1250,"height":2500,"thickness":0.4,"outputs":[{"partName":"SIDE (1884x566)","qty":2},{"partName":"SHELF (510x890)","qty":1},{"partName":"LOCKER COVER","qty":2},{"partName":"SIDE SUPPORT (80x1730)","qty":1}]}]'::jsonb, 'per-unit', 0, '2026-09-11T13:18:25.149Z'::timestamptz)
on conflict (model_name, plan_name) do update set
  sheets = excluded.sheets, plan_type = excluded.plan_type,
  base_qty = excluded.base_qty, updated_at = excluded.updated_at;
insert into cutting_plans (model_name, plan_name, sheets, plan_type, base_qty, updated_at) values (
  '3004', 'Plan 2', '[]'::jsonb, 'per-unit', 0, '2026-09-13T06:18:16.763Z'::timestamptz)
on conflict (model_name, plan_name) do update set
  sheets = excluded.sheets, plan_type = excluded.plan_type,
  base_qty = excluded.base_qty, updated_at = excluded.updated_at;

-- plan_versions
insert into plan_versions (version_id, model_name, version_number, source_plan_name, sheets, created_at, note) values (
  'PV-8b4737f97d', '3004', 1, 'Plan 1',
  '[{"width":900,"height":2500,"thickness":"0.35","outputs":[{"partName":"BACK (883x1874)","qty":1,"size":"883x1877"},{"partName":"BOTTOM (893x582)","qty":1,"size":"891x586"}]},{"width":"900","height":2500,"thickness":0.45,"outputs":[{"partName":"SHELF (510x890)","qty":4},{"partName":"LOCKER COVER","qty":"2","isExtra":false,"size":"313X367"},{"partName":"","qty":"1","isExtra":true,"size":"120X409"},{"partName":"","qty":"","isExtra":true,"size":"68X409"}]},{"width":"1000","height":2500,"thickness":0.45,"outputs":[{"partName":"DOOR L (477x1850)","qty":1,"size":"473X1847"},{"partName":"DOOR R (467x1850)","qty":1,"size":"463X1847"},{"partName":"TOP (893x582)","qty":1,"size":"891X601"},{"partName":"Shelf rip","qty":2,"isExtra":true,"size":"60X840"},{"partName":"Shelf rip ","qty":1,"isExtra":true,"size":"60X753"}]},{"width":1250,"height":2500,"thickness":"0.35","outputs":[{"partName":"SIDE (1884x566)","qty":2,"size":"1882X586"},{"partName":"SHELF (510x890)","qty":1,"size":"506X889"},{"partName":"Self support","qty":1,"isExtra":true,"size":"97X840"},{"partName":"Self rip","qty":"2","isExtra":true,"size":"60X840"}]},{"width":"1000","height":"2500","thickness":"0.45","outputs":[{"partName":"Half shelf","qty":"4","isExtra":true,"size":"461X506"},{"partName":"Partition","qty":"3","isExtra":true,"size":"485X960"},{"partName":"","qty":"1","isExtra":true,"size":"615X60"}]}]'::jsonb, '2026-09-12T10:40:03.523Z'::timestamptz, 'Modified for PO-0001')
on conflict (version_id) do update set
  sheets = excluded.sheets, note = excluded.note;

-- orders
insert into orders (
  po_number, model_name, plan_name, qty, dxf_ref_no, colour_plan,
  delivery_deadline, party_name, plan_version_id,
  sheet_completion, bending_completion, total_sheets_required,
  cutting_status, bending_status, created_at,
  multi_yield_decisions, sheet_stock_consumed,
  plan_type, bulk_base_qty, bulk_multiplier,
  sheet_qty_overrides, bending_leftover_consumed, extra_bending_completion,
  plan_entry_inventory_moves,
  sheet_completion_meta, bending_completion_meta, extra_bending_completion_meta
) values (
  'PO-0001', '3004', 'Plan 1', 50,
  'N/A', 'N/A', '2026-09-14', 'N/A',
  'PV-8b4737f97d',
  '[true,true,true,true,true]'::jsonb,
  '[false,false,false,false,false,false,false,false,false,false,false,false]'::jsonb,
  201,
  'complete', 'pending', '2026-09-12T05:51:08.501Z'::timestamptz,
  '{}'::jsonb,
  '{"0":true,"1":true,"2":true,"3":true,"4":true}'::jsonb,
  'per-unit', 0, 0,
  '{"0":50,"1":37,"2":50,"3":50,"4":14}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{"1":{"at":"2026-09-13T09:19:06.884Z","by":"ABHISHEK"},"4":{"at":"2026-09-16T05:24:17.306Z","by":"ABHISHEK"}}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb
)
on conflict (po_number) do update set
  sheet_completion = excluded.sheet_completion,
  bending_completion = excluded.bending_completion,
  cutting_status = excluded.cutting_status,
  bending_status = excluded.bending_status,
  sheet_qty_overrides = excluded.sheet_qty_overrides,
  plan_entry_inventory_moves = excluded.plan_entry_inventory_moves;

-- cutting_extras
-- (none)

-- extra_part_inventory
-- (none)

-- extra_inventory_log
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-bb18cdd499', '__XXTEST_ADDSHEET__', 'PartA', '', 9,
  'cut-surplus', 'PO-0002', 'Admin', '2026-09-14T04:14:31.994Z'::timestamptz, 'Surplus from Sheet 3 cut')
on conflict (log_id) do nothing;
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-a684240d53', '__XXTEST_SHORT__', 'ShortPart', '55x66', 40,
  'logged-extra', 'PO-0003', 'Admin', '2026-09-18T06:40:17.481Z'::timestamptz, 'Logged at cutting')
on conflict (log_id) do nothing;
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-343c8e74ec', '__XXTEST_SHORT__', 'ShortPart', '55x66', -5,
  'pulled-into-bending', 'PO-0002', 'Admin', '2026-09-18T07:09:21.598Z'::timestamptz, 'Pulled into this PO''s bending queue')
on conflict (log_id) do nothing;
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-fa4248ee16', '__XXTEST_SHORT__', 'ShortPart', '55x66', -25,
  'pulled-into-bending', 'PO-0002', 'Admin', '2026-09-18T07:10:03.980Z'::timestamptz, 'Pulled into this PO''s bending queue')
on conflict (log_id) do nothing;
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-75ce7e0925', '__XXTEST_SHORT__', 'ShortPart', '55x66', 50,
  'logged-extra', 'PO-0003', 'Admin', '2026-09-18T07:15:18.766Z'::timestamptz, 'Logged at cutting')
on conflict (log_id) do nothing;
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-2c3b3b457f', '__XXTEST_SHORT__', 'ShortPart', '55x66', -5,
  'pulled-into-bending', 'PO-0004', 'Admin', '2026-09-18T07:19:28.803Z'::timestamptz, 'Pulled into this PO''s bending queue')
on conflict (log_id) do nothing;
insert into extra_inventory_log (log_id, model_name, part_name, size, delta, reason, po_number, actor, timestamp, note) values (
  'EIL-3a55a2c7d2', '__XXTEST_SHORT__', 'ShortPart', '55x66', -25,
  'pulled-into-bending', 'PO-0004', 'Admin', '2026-09-18T07:20:07.944Z'::timestamptz, 'Pulled into this PO''s bending queue')
on conflict (log_id) do nothing;

-- sheet_stock
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.3', 900, 2500, 0.3, 0, '2026-09-13T04:30:12.197Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.35', 900, 2500, 0.35, 79, '2026-09-13T04:30:12.639Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.4', 900, 2500, 0.4, 60, '2026-09-13T04:30:13.173Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.45', 900, 2500, 0.45, 567, '2026-09-14T04:17:25.535Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.5', 900, 2500, 0.5, 0, '2026-09-13T04:30:14.274Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1000x2500x0.55', 1000, 2500, 0.55, 109, '2026-09-13T04:30:14.826Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.6', 900, 2500, 0.6, 0, '2026-09-13T04:30:15.346Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1000x2500x0.6', 1000, 2500, 0.6, 11, '2026-09-13T04:30:16.148Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.7', 900, 2500, 0.7, 0, '2026-09-13T04:30:16.679Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.8', 900, 2500, 0.8, 0, '2026-09-13T04:30:19.657Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1000x2500x0.8', 1000, 2500, 0.8, 0, '2026-09-13T04:30:20.096Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '900x2500x0.9', 900, 2500, 0.9, 0, '2026-09-13T04:30:20.607Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.3', 1250, 2500, 0.3, 0, '2026-09-13T04:30:21.106Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.35', 1250, 2500, 0.35, 102, '2026-09-13T04:30:22.434Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.4', 1250, 2500, 0.4, 0, '2026-09-13T04:30:23.416Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.45', 1250, 2500, 0.45, 0, '2026-09-13T04:30:25.660Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.6', 1250, 2500, 0.6, 232, '2026-09-13T04:30:27.088Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.7', 1250, 2500, 0.7, 26, '2026-09-13T04:30:27.613Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.8', 1250, 2500, 0.8, 44, '2026-09-13T04:30:28.695Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  'CR Sheet Mix', 0, 0, 0, 116, '2026-09-13T04:30:29.299Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1000x2500x0.7', 1000, 2500, 0.7, 0, '2026-09-13T04:30:18.537Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1000x2500x0.45', 1000, 2500, 0.45, 636, '2026-09-16T05:24:17.707Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x2', 1250, 2500, 2, 17, '2026-09-13T04:30:29.794Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  'HR Sheet 2.0mm 5FT', 0, 0, 0, 0, '2026-09-13T04:30:31.180Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;
insert into sheet_stock (size, width, height, thickness, qty, updated_at) values (
  '1250x2500x0.5', 1250, 2500, 0.5, 430, '2026-09-14T04:17:29.606Z'::timestamptz)
on conflict (size) do update set
  qty = excluded.qty, updated_at = excluded.updated_at;

-- sheet_stock_log
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-b9b7bcc452', '900x2500x0.5', -50, 'po-cut', 'PO-0001', '2026-09-12T10:29:45.613Z'::timestamptz, 'Sheet 3 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-bd1953ae9e', '900x2500x0.45', -50, 'po-cut', 'PO-0001', '2026-09-12T10:36:13.649Z'::timestamptz, 'Sheet 1 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-1df37e3105', '1250x2500x0.4', -50, 'po-cut', 'PO-0001', '2026-09-12T10:39:41.445Z'::timestamptz, 'Sheet 4 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-54807ea603', '900x2500x0.45', -50, 'po-cut', 'PO-0001', '2026-09-12T10:54:27.083Z'::timestamptz, 'Sheet 1 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-a068a340a2', '900x2500x0.45', -50, 'po-cut', 'PO-0001', '2026-09-12T10:55:43.415Z'::timestamptz, 'Sheet 3 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-d6fb24a702', '1250x2500x0.4', -50, 'po-cut', 'PO-0001', '2026-09-12T10:56:13.767Z'::timestamptz, 'Sheet 4 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-4b49c31627', '900x2500x0.45', -37, 'po-cut', 'PO-0001', '2026-09-12T12:41:08.586Z'::timestamptz, 'Sheet 2 cut')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-92e0677c7a', '900x2500x0.3', 0, 'initial-stock-load', '', '2026-09-13T04:16:59.794Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-648cbcc3ef', '900x2500x0.35', 79, 'initial-stock-load', '', '2026-09-13T04:17:00.597Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-7393cf1037', '900x2500x0.4', 60, 'initial-stock-load', '', '2026-09-13T04:17:01.163Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-b0e13dc49e', '900x2500x0.45', 567, 'initial-stock-load', '', '2026-09-13T04:17:01.752Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-15d815155a', '900x2500x0.5', 0, 'initial-stock-load', '', '2026-09-13T04:17:02.376Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-d75b543ab8', '1000x2500x0.55', 191, 'initial-stock-load', '', '2026-09-13T04:17:03.985Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-11aff0245d', '900x2500x0.6', 0, 'initial-stock-load', '', '2026-09-13T04:17:04.877Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-1944cf3bb8', '1000x2500x0.6', 11, 'initial-stock-load', '', '2026-09-13T04:17:05.453Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-b8fd58e5b2', '900x2500x0.7', 0, 'initial-stock-load', '', '2026-09-13T04:17:06.275Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-c8f5855f79', '900x2500x0.8', 0, 'initial-stock-load', '', '2026-09-13T04:17:07.552Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-0437b64709', '1000x2500x0.8', 0, 'initial-stock-load', '', '2026-09-13T04:17:08.137Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-7e9b9fbcc1', '900x2500x0.9', 0, 'initial-stock-load', '', '2026-09-13T04:17:09.003Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-4c21b127f6', '1250x2500x0.3', 0, 'initial-stock-load', '', '2026-09-13T04:17:09.564Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-0daae12dbd', '1250x2500x0.35', 102, 'initial-stock-load', '', '2026-09-13T04:17:10.207Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-67e6864773', '1250x2500x0.4', 0, 'initial-stock-load', '', '2026-09-13T04:17:10.752Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-52a3ae17eb', '1250x2500x0.45', 650, 'initial-stock-load', '', '2026-09-13T04:17:11.809Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-475ea6da10', '1250x2500x0.5', 430, 'initial-stock-load', '', '2026-09-13T04:17:12.333Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-d928ae1bd3', '1250x2500x0.6', 228, 'initial-stock-load', '', '2026-09-13T04:17:12.917Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-138d58f76b', '1250x2500x0.7', 27, 'initial-stock-load', '', '2026-09-13T04:17:13.409Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-1a8966d3a8', '1250x2500x0.8', 44, 'initial-stock-load', '', '2026-09-13T04:17:14.184Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-3a8bf9cee2', 'CR Sheet Mix', 116, 'initial-stock-load', '', '2026-09-13T04:17:15.302Z'::timestamptz, 'Initial real stock load')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-6c5a78844a', '900x2500x0.3', 0, 'stock-correction', '', '2026-09-13T04:30:12.539Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-9048083a54', '900x2500x0.35', 79, 'stock-correction', '', '2026-09-13T04:30:13.058Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-51455a4548', '900x2500x0.4', 60, 'stock-correction', '', '2026-09-13T04:30:13.617Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-bd2137ee56', '900x2500x0.45', 567, 'stock-correction', '', '2026-09-13T04:30:14.141Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-feac70287e', '900x2500x0.5', 0, 'stock-correction', '', '2026-09-13T04:30:14.693Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-848459b12f', '1000x2500x0.55', 109, 'stock-correction', '', '2026-09-13T04:30:15.235Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-80c31186f7', '900x2500x0.6', 0, 'stock-correction', '', '2026-09-13T04:30:15.798Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-f3edde9b53', '1000x2500x0.6', 11, 'stock-correction', '', '2026-09-13T04:30:16.564Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-ff0ad2d23f', '900x2500x0.7', 0, 'stock-correction', '', '2026-09-13T04:30:18.425Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-feed1beff4', '1000x2500x0.7', 0, 'stock-correction', '', '2026-09-13T04:30:18.719Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-d686f31692', '900x2500x0.8', 0, 'stock-correction', '', '2026-09-13T04:30:19.994Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-a6e386d915', '1000x2500x0.8', 0, 'stock-correction', '', '2026-09-13T04:30:20.501Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-770e4d4d0d', '900x2500x0.9', 0, 'stock-correction', '', '2026-09-13T04:30:20.995Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-c1e7eb90cb', '1250x2500x0.3', 0, 'stock-correction', '', '2026-09-13T04:30:22.310Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-3f45a10317', '1250x2500x0.35', 102, 'stock-correction', '', '2026-09-13T04:30:23.322Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-b635e204e7', '1250x2500x0.4', 0, 'stock-correction', '', '2026-09-13T04:30:23.823Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-a73c30dd7a', '1000x2500x0.45', 650, 'stock-correction', '', '2026-09-13T04:30:24.114Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-0dee980197', '1250x2500x0.45', 0, 'stock-correction', '', '2026-09-13T04:30:26.434Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-c917e1c81a', '1250x2500x0.5', 430, 'stock-correction', '', '2026-09-13T04:30:26.971Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-4f70f994de', '1250x2500x0.6', 232, 'stock-correction', '', '2026-09-13T04:30:27.518Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-676e5edbb6', '1250x2500x0.7', 26, 'stock-correction', '', '2026-09-13T04:30:28.460Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-f1c8bb74d6', '1250x2500x0.8', 44, 'stock-correction', '', '2026-09-13T04:30:29.072Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-0ce3e17209', 'CR Sheet Mix', 116, 'stock-correction', '', '2026-09-13T04:30:29.690Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-ccb078a427', '1250x2500x2', 17, 'stock-correction', '', '2026-09-13T04:30:29.957Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-76f80824ae', 'HR Sheet 2.0mm 5FT', 0, 'stock-correction', '', '2026-09-13T04:30:31.287Z'::timestamptz, 'Corrected stock list with SKU codes - fixes 0.55mm MTRx8, moves 650pcs 0.45mm from 4x8 to MTRx8, adjusts 0.60/0.70mm 4x8, adds HR Sheet material and 0.70mm MTRx8')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-e407c332b9', '900x2500x0.45', 2, 'adjustment', '', '2026-09-14T04:17:26.068Z'::timestamptz, 'Reverse test deduction - restore to counted 567')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-c454869c9c', '1250x2500x0.5', 430, 'received', '', '2026-09-14T04:17:29.763Z'::timestamptz, 'Restore row removed during testing - counted qty 430')
on conflict (log_id) do nothing;
insert into sheet_stock_log (log_id, size, delta, reason, po_number, timestamp, note) values (
  'SL-fcf6e97e82', '1000x2500x0.45', -14, 'po-cut', 'PO-0001', '2026-09-16T05:24:18.427Z'::timestamptz, 'Sheet 5 cut')
on conflict (log_id) do nothing;

-- profiles (permissions carried across exactly as they are today)
insert into profiles (id, username, role, permissions, created_at, created_by)
select u.id, 'Admin', 'admin',
       '{}'::jsonb,
       '2026-09-11T11:54:09.324Z'::timestamptz, ''
from auth.users u where u.email = 'admin@almirah.local'
on conflict (id) do update set
  username = excluded.username, role = excluded.role,
  permissions = excluded.permissions;
insert into profiles (id, username, role, permissions, created_at, created_by)
select u.id, 'ABHISHEK', 'user',
       '{"cuttingConfig":"none","orders":"none","cuttingStage":"edit","bendingStage":"edit","extraInventory":"view","sheetStock":"view"}'::jsonb,
       '2026-09-11T11:57:52.136Z'::timestamptz, 'Admin'
from auth.users u where u.email = 'abhishek@almirah.local'
on conflict (id) do update set
  username = excluded.username, role = excluded.role,
  permissions = excluded.permissions;

-- Re-seed the PO sequence now that orders exist, so the next created PO
-- cannot collide with one already in the Sheet.
select setval('po_number_seq', greatest(
  coalesce((select max((regexp_replace(po_number, '\D', '', 'g'))::bigint)
            from orders where po_number ~ '^PO-\d+$'), 0), 1));

-- Verification: every count here must match the Sheet.
select 'models' t, count(*) from models
union all select 'cutting_plans', count(*) from cutting_plans
union all select 'plan_versions', count(*) from plan_versions
union all select 'orders', count(*) from orders
union all select 'cutting_extras', count(*) from cutting_extras
union all select 'extra_part_inventory', count(*) from extra_part_inventory
union all select 'extra_inventory_log', count(*) from extra_inventory_log
union all select 'sheet_stock', count(*) from sheet_stock
union all select 'sheet_stock_log', count(*) from sheet_stock_log
union all select 'profiles', count(*) from profiles
order by 1;
